package testkube

import "time"

// Execution represents a test execution
type Execution struct {
	ID           string
	Name         string // Execution number/name
	WorkflowName string
	Status       string // passed, failed, running, queued
	StartTime    time.Time
	EndTime      time.Time
	Duration     time.Duration
	Branch       string
	Labels       map[string]string
}

// Workflow represents a test workflow
type Workflow struct {
	Name      string
	Namespace string
	Type      string // playwright, vitest, k6
	Created   time.Time
}

// Artifact represents a file generated by an execution
type Artifact struct {
	Name string
	Size int64
	Path string
}

type ListOptions struct {
	PageSize int
	Page     int
	Status   string
	Workflow string
}

type Client interface {
	GetExecutions(opts ListOptions) ([]Execution, error)
	GetExecution(id string) (*Execution, error)
	GetWorkflows() ([]Workflow, error)
	GetArtifacts(executionID string) ([]Artifact, error)
	DownloadArtifact(executionID, path string) ([]byte, error)
}
